import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { defaultCorpusRoot, loadCorpus } from '../corpus/loadCorpus';
import { BaselineMatcher } from '../matchers/baseline';
import { FuzzyMatcher } from '../matchers/fuzzy';
import type { Matcher } from '../matchers/types';
import { replay, type ReplayReport } from '../replay';
import { formatReport } from '../report';
import { constructionChristmasTriggers } from '../triggers';

const FOOTER = '\n---\n_Generated by `npm run replay`. Do not edit by hand._\n';

const trials = loadCorpus(defaultCorpusRoot());
const incomplete = trials.filter((t) => !t.completeness.ok);

function run(matcher: Matcher, outFile: string): ReplayReport {
  const report = replay(trials, constructionChristmasTriggers, matcher);
  const md = formatReport(report);
  writeFileSync(fileURLToPath(new URL(`../../${outFile}`, import.meta.url)), md + FOOTER);
  console.log(md);
  return report;
}

const baseline = run(new BaselineMatcher(), 'BASELINE.md');
const fuzzy = run(new FuzzyMatcher(), 'FUZZY.md');
const fuzzyRegressed = fuzzy.results.filter((r) => !r.fired && r.trial.meta.success).length;

console.log(`Loaded ${trials.length} trials; ${incomplete.length} incomplete.`);

const problems: string[] = [];
if (incomplete.length !== 0) {
  problems.push(`${incomplete.length} incomplete trial(s)`);
}
if (baseline.totalMismatches !== 0) {
  problems.push(`baseline differs from recorded success in ${baseline.totalMismatches} trial(s)`);
}
if (fuzzy.totalFalseFires !== 0) {
  problems.push(`fuzzy produced ${fuzzy.totalFalseFires} false fire(s)`);
}
if (fuzzyRegressed !== 0) {
  problems.push(`fuzzy regressed ${fuzzyRegressed} Phase 1 success(es)`);
}

if (problems.length !== 0) {
  console.error(`✗ ${problems.join('; ')}`);
  process.exit(1);
}
console.log(
  `✓ baseline reproduced (0 diffs); fuzzy ${fuzzy.totalFired}/${fuzzy.totalTrials} fired, 0 false fires, 0 regressions.`,
);
