import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { defaultCorpusRoot, loadCorpus } from '../corpus/loadCorpus';
import { BaselineMatcher } from '../matchers/baseline';
import { replay } from '../replay';
import { formatReport } from '../report';
import { constructionChristmasTriggers } from '../triggers';

const trials = loadCorpus(defaultCorpusRoot());
const incomplete = trials.filter((t) => !t.completeness.ok);
const report = replay(trials, constructionChristmasTriggers, new BaselineMatcher());

const footer =
  '\n---\n_Generated by `npm run replay` (matcher: baseline-substring). Do not edit by hand._\n';
const md = formatReport(report) + footer;

const outPath = fileURLToPath(new URL('../../BASELINE.md', import.meta.url));
writeFileSync(outPath, md);

console.log(md);
console.log(`Loaded ${trials.length} trials; ${incomplete.length} incomplete.`);

if (incomplete.length !== 0) {
  console.error(
    `✗ Incomplete trials: ${incomplete.map((t) => `${t.provider}/${t.slug}/${t.trialNumber}`).join(', ')}`,
  );
  process.exit(1);
}
if (report.totalMismatches !== 0) {
  console.error(
    `✗ ${report.totalMismatches} mismatch(es) vs recorded success — harness does NOT reproduce Phase 1.`,
  );
  process.exit(1);
}
console.log(`✓ Baseline reproduced with 0 mismatches. Wrote ${outPath}`);
