/* This file is generated by scripts/build-content.ts. */

export const contentAssets = {
  'construction-christmas/sounds/boom.wav': require('../books/construction-christmas/sounds/boom.wav'),
  'construction-christmas/sounds/latency-click.wav': require('../books/construction-christmas/sounds/latency-click.wav'),
  'construction-christmas/sounds/sparkle.wav': require('../books/construction-christmas/sounds/sparkle.wav'),
  'construction-christmas/sounds/truck.wav': require('../books/construction-christmas/sounds/truck.wav'),
} as const;

export type ContentAssetPath = keyof typeof contentAssets;
