/* This file is generated by scripts/build-content.ts. */

import type { CompiledBook } from '../../src/content/types';

export const compiledBooks = {
  'construction-christmas': require('./construction-christmas.book.json') as CompiledBook,
} as const;

export type CompiledBookId = keyof typeof compiledBooks;
